(cl:defpackage basic-srv
  (:use )
  (:export
   "SERVICEEXAMPLE"
   "<SERVICEEXAMPLE-REQUEST>"
   "SERVICEEXAMPLE-REQUEST"
   "<SERVICEEXAMPLE-RESPONSE>"
   "SERVICEEXAMPLE-RESPONSE"
   "ADDTWOINT"
   "<ADDTWOINT-REQUEST>"
   "ADDTWOINT-REQUEST"
   "<ADDTWOINT-RESPONSE>"
   "ADDTWOINT-RESPONSE"
  ))

