// Generated by gencpp from file basic/addtwoint.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_ADDTWOINT_H
#define BASIC_MESSAGE_ADDTWOINT_H

#include <ros/service_traits.h>


#include <basic/addtwointRequest.h>
#include <basic/addtwointResponse.h>


namespace basic
{

struct addtwoint
{

typedef addtwointRequest Request;
typedef addtwointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addtwoint
} // namespace basic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic::addtwoint > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::basic::addtwoint&) { return value(); }
};

template<>
struct DataType< ::basic::addtwoint > {
  static const char* value()
  {
    return "basic/addtwoint";
  }

  static const char* value(const ::basic::addtwoint&) { return value(); }
};


// service_traits::MD5Sum< ::basic::addtwointRequest> should match
// service_traits::MD5Sum< ::basic::addtwoint >
template<>
struct MD5Sum< ::basic::addtwointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic::addtwoint >::value();
  }
  static const char* value(const ::basic::addtwointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::addtwointRequest> should match
// service_traits::DataType< ::basic::addtwoint >
template<>
struct DataType< ::basic::addtwointRequest>
{
  static const char* value()
  {
    return DataType< ::basic::addtwoint >::value();
  }
  static const char* value(const ::basic::addtwointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic::addtwointResponse> should match
// service_traits::MD5Sum< ::basic::addtwoint >
template<>
struct MD5Sum< ::basic::addtwointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic::addtwoint >::value();
  }
  static const char* value(const ::basic::addtwointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::addtwointResponse> should match
// service_traits::DataType< ::basic::addtwoint >
template<>
struct DataType< ::basic::addtwointResponse>
{
  static const char* value()
  {
    return DataType< ::basic::addtwoint >::value();
  }
  static const char* value(const ::basic::addtwointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_MESSAGE_ADDTWOINT_H
