// Generated by gencpp from file basic/addtwointRequest.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_ADDTWOINTREQUEST_H
#define BASIC_MESSAGE_ADDTWOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic
{
template <class ContainerAllocator>
struct addtwointRequest_
{
  typedef addtwointRequest_<ContainerAllocator> Type;

  addtwointRequest_()
    : a(0)
    , b(0)  {
    }
  addtwointRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::basic::addtwointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic::addtwointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addtwointRequest_

typedef ::basic::addtwointRequest_<std::allocator<void> > addtwointRequest;

typedef boost::shared_ptr< ::basic::addtwointRequest > addtwointRequestPtr;
typedef boost::shared_ptr< ::basic::addtwointRequest const> addtwointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic::addtwointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic::addtwointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic::addtwointRequest_<ContainerAllocator1> & lhs, const ::basic::addtwointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic::addtwointRequest_<ContainerAllocator1> & lhs, const ::basic::addtwointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::basic::addtwointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic::addtwointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::addtwointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::addtwointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::addtwointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::addtwointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic::addtwointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::basic::addtwointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::basic::addtwointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic/addtwointRequest";
  }

  static const char* value(const ::basic::addtwointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic::addtwointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a \n"
"int64 b\n"
;
  }

  static const char* value(const ::basic::addtwointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic::addtwointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addtwointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic::addtwointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic::addtwointRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_MESSAGE_ADDTWOINTREQUEST_H
