// Generated by gencpp from file basic/addtwointResponse.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_ADDTWOINTRESPONSE_H
#define BASIC_MESSAGE_ADDTWOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic
{
template <class ContainerAllocator>
struct addtwointResponse_
{
  typedef addtwointResponse_<ContainerAllocator> Type;

  addtwointResponse_()
    : sum(0)  {
    }
  addtwointResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::basic::addtwointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic::addtwointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addtwointResponse_

typedef ::basic::addtwointResponse_<std::allocator<void> > addtwointResponse;

typedef boost::shared_ptr< ::basic::addtwointResponse > addtwointResponsePtr;
typedef boost::shared_ptr< ::basic::addtwointResponse const> addtwointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic::addtwointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic::addtwointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic::addtwointResponse_<ContainerAllocator1> & lhs, const ::basic::addtwointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic::addtwointResponse_<ContainerAllocator1> & lhs, const ::basic::addtwointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::basic::addtwointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic::addtwointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::addtwointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::addtwointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::addtwointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::addtwointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic::addtwointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::basic::addtwointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic::addtwointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic/addtwointResponse";
  }

  static const char* value(const ::basic::addtwointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic::addtwointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
"\n"
;
  }

  static const char* value(const ::basic::addtwointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic::addtwointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addtwointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic::addtwointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic::addtwointResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_MESSAGE_ADDTWOINTRESPONSE_H
