// Generated by gencpp from file basic/ServiceExample.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_SERVICEEXAMPLE_H
#define BASIC_MESSAGE_SERVICEEXAMPLE_H

#include <ros/service_traits.h>


#include <basic/ServiceExampleRequest.h>
#include <basic/ServiceExampleResponse.h>


namespace basic
{

struct ServiceExample
{

typedef ServiceExampleRequest Request;
typedef ServiceExampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceExample
} // namespace basic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic::ServiceExample > {
  static const char* value()
  {
    return "b6541b31be965d2ea76445e10907a742";
  }

  static const char* value(const ::basic::ServiceExample&) { return value(); }
};

template<>
struct DataType< ::basic::ServiceExample > {
  static const char* value()
  {
    return "basic/ServiceExample";
  }

  static const char* value(const ::basic::ServiceExample&) { return value(); }
};


// service_traits::MD5Sum< ::basic::ServiceExampleRequest> should match
// service_traits::MD5Sum< ::basic::ServiceExample >
template<>
struct MD5Sum< ::basic::ServiceExampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic::ServiceExample >::value();
  }
  static const char* value(const ::basic::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::ServiceExampleRequest> should match
// service_traits::DataType< ::basic::ServiceExample >
template<>
struct DataType< ::basic::ServiceExampleRequest>
{
  static const char* value()
  {
    return DataType< ::basic::ServiceExample >::value();
  }
  static const char* value(const ::basic::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic::ServiceExampleResponse> should match
// service_traits::MD5Sum< ::basic::ServiceExample >
template<>
struct MD5Sum< ::basic::ServiceExampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic::ServiceExample >::value();
  }
  static const char* value(const ::basic::ServiceExampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic::ServiceExampleResponse> should match
// service_traits::DataType< ::basic::ServiceExample >
template<>
struct DataType< ::basic::ServiceExampleResponse>
{
  static const char* value()
  {
    return DataType< ::basic::ServiceExample >::value();
  }
  static const char* value(const ::basic::ServiceExampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_MESSAGE_SERVICEEXAMPLE_H
