// Generated by gencpp from file basic/ServiceExampleRequest.msg
// DO NOT EDIT!


#ifndef BASIC_MESSAGE_SERVICEEXAMPLEREQUEST_H
#define BASIC_MESSAGE_SERVICEEXAMPLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic
{
template <class ContainerAllocator>
struct ServiceExampleRequest_
{
  typedef ServiceExampleRequest_<ContainerAllocator> Type;

  ServiceExampleRequest_()
    : onezero(0)  {
    }
  ServiceExampleRequest_(const ContainerAllocator& _alloc)
    : onezero(0)  {
  (void)_alloc;
    }



   typedef int32_t _onezero_type;
  _onezero_type onezero;





  typedef boost::shared_ptr< ::basic::ServiceExampleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic::ServiceExampleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceExampleRequest_

typedef ::basic::ServiceExampleRequest_<std::allocator<void> > ServiceExampleRequest;

typedef boost::shared_ptr< ::basic::ServiceExampleRequest > ServiceExampleRequestPtr;
typedef boost::shared_ptr< ::basic::ServiceExampleRequest const> ServiceExampleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic::ServiceExampleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic::ServiceExampleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic::ServiceExampleRequest_<ContainerAllocator1> & lhs, const ::basic::ServiceExampleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.onezero == rhs.onezero;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic::ServiceExampleRequest_<ContainerAllocator1> & lhs, const ::basic::ServiceExampleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::basic::ServiceExampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic::ServiceExampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::ServiceExampleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic::ServiceExampleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::ServiceExampleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic::ServiceExampleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic::ServiceExampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bd5e0f9ac4159bea0d24a22a826c13c";
  }

  static const char* value(const ::basic::ServiceExampleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bd5e0f9ac4159beULL;
  static const uint64_t static_value2 = 0xa0d24a22a826c13cULL;
};

template<class ContainerAllocator>
struct DataType< ::basic::ServiceExampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic/ServiceExampleRequest";
  }

  static const char* value(const ::basic::ServiceExampleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic::ServiceExampleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 onezero\n"
;
  }

  static const char* value(const ::basic::ServiceExampleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic::ServiceExampleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.onezero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceExampleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic::ServiceExampleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic::ServiceExampleRequest_<ContainerAllocator>& v)
  {
    s << indent << "onezero: ";
    Printer<int32_t>::stream(s, indent + "  ", v.onezero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_MESSAGE_SERVICEEXAMPLEREQUEST_H
